### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by RazerM** [lnqs/textual-image#28]
There are no license file at the project root. I notice the Python classifiers have GPL, and while MIT was once there [it was removed](https://github.com/lnqs/textual-image/commit/3dc01907e8dc005e34f567b80915e0ac0d91dd5e#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L22).

Would you consider releasing it under MIT or LGPL?

**Comment by lnqs** [comment]
I actually haven't thought about the licensing too much and added GPL out of habit. The MIT was added due to copying some classifiers from somewhere else and not cleaning them up correctly.
But, yeah, LGPL makes way more sense for this package than GPL. Update is on the way.
